### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/hafas-monitor-trips#5]
```js
const createHafas = require('bvg-hafas')
const createMonitor = require('hafas-monitor-trips')

const centerOfBerlin = {
	north: 52.55,
	west: 13.31,
	south: 52.48,
	east: 13.48
}
const hafas = createHafas('hafas-gtfs-rt-feed example')
const monitor = createMonitor(hafas, centerOfBerlin, 20 * 1000)
monitor.once('error', err => console.error(err.message))
```

```
(node:2199) UnhandledPromiseRejectionWarning: Error: HCI Service: problems during service execution
    at Object.request (/Users/j/web/hafas-gtfs-rt-feed/node_modules/hafas-client/lib/request.js:81:14)
    at Object.trip (/Users/j/web/hafas-gtfs-rt-feed/node_modules/hafas-client/index.js:349:18)
    at /Users/j/web/hafas-gtfs-rt-feed/node_modules/hafas-monitor-trips/index.js:105:23
    at run (/Users/j/web/hafas-gtfs-rt-feed/node_modules/p-queue/dist/index.js:249:104)
    at PQueue._tryToStartAnother (/Users/j/web/hafas-gtfs-rt-feed/node_modules/p-queue/dist/index.js:197:38)
    at PQueue._next (/Users/j/web/hafas-gtfs-rt-feed/node_modules/p-queue/dist/index.js:146:14)
    at run (/Users/j/web/hafas-gtfs-rt-feed/node_modules/p-queue/dist/index.js:260:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2199) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

```
hafas-gtfs-rt-feed@0.2.0 /Users/j/web/hafas-gtfs-rt-feed
├─┬ bvg-hafas@3.0.0
│ └─┬ hafas-client@5.2.0
│   ├── @derhuerst/br2nl@1.0.0
│   ├── capture-stack-trace@1.0.1
│   ├─┬ create-hash@1.2.0
│   │ ├─┬ cipher-base@1.0.4
│   │ │ ├── inherits@2.0.4 deduped
│   │ │ └── safe-buffer@5.2.0 deduped
│   │ ├── inherits@2.0.4 deduped
│   │ ├─┬ md5.js@1.3.5
│   │ │ ├─┬ hash-base@3.0.4
│   │ │ │ ├── inherits@2.0.4 deduped
│   │ │ │ └── safe-buffer@5.2.0 deduped
│   │ │ ├── inherits@2.0.4 deduped
│   │ │ └── safe-buffer@5.2.0 deduped
│   │ ├─┬ ripemd160@2.0.2
│   │ │ ├── hash-base@3.0.4 deduped
│   │ │ └── inherits@2.0.4 deduped
│   │ └─┬ sha.js@2.4.11
│   │   ├── inherits@2.0.4 deduped
│   │   └── safe-buffer@5.2.0 deduped
│   ├─┬ fetch-ponyfill@6.1.0
│   │ └── node-fetch@2.6.0
│   ├── google-polyline@1.0.3
│   ├── gps-distance@0.0.4
│   ├── lodash@4.17.15
│   ├── luxon@1.22.0
│   ├── object-scan@11.0.1
│   ├─┬ p-retry@4.2.0
│   │ ├── @types/retry@0.12.0
│   │ └── retry@0.12.0
│   ├── p-throttle@3.1.0
│   ├─┬ pinkie-promise@2.0.1
│   │ └── pinkie@2.0.4
│   ├── qs@6.9.1
│   ├── slugg@1.2.1
│   ├── vbb-parse-line@1.0.0
│   ├── vbb-parse-ticket@0.2.1
│   ├── vbb-short-station-name@1.0.1
│   ├─┬ vbb-stations@7.2.0
│   │ └── lodash.get@4.4.2
│   └── vbb-translate-ids@4.0.0
├─┬ gtfs-rt-bindings@3.0.0
│ └─┬ protocol-buffers-encodings@1.1.0
│   ├─┬ signed-varint@2.0.1
│   │ └── varint@5.0.0 deduped
│   └── varint@5.0.0 deduped
├─┬ hafas-monitor-trips@3.0.0
│ ├─┬ @turf/boolean-within@6.0.1
│ │ ├─┬ @turf/bbox@6.0.1
│ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ └─┬ @turf/meta@6.0.2
│ │ │   └── @turf/helpers@6.1.4 deduped
│ │ ├─┬ @turf/boolean-point-in-polygon@6.0.1
│ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ └── @turf/invariant@6.1.2 deduped
│ │ ├─┬ @turf/boolean-point-on-line@6.0.1
│ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ └── @turf/invariant@6.1.2 deduped
│ │ ├── @turf/helpers@6.1.4 deduped
│ │ └─┬ @turf/invariant@6.1.2
│ │   └── @turf/helpers@6.1.4 deduped
│ ├─┬ @turf/distance@6.0.1
│ │ ├── @turf/helpers@6.1.4 deduped
│ │ └── @turf/invariant@6.1.2 deduped
│ ├── @turf/helpers@6.1.4
│ ├─┬ @turf/square-grid@6.0.2
│ │ ├─┬ @turf/boolean-intersects@6.0.2
│ │ │ ├─┬ @turf/boolean-disjoint@6.0.2
│ │ │ │ ├── @turf/boolean-point-in-polygon@6.0.1 deduped
│ │ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ │ ├─┬ @turf/line-intersect@6.0.2
│ │ │ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ │ │ ├── @turf/invariant@6.1.2 deduped
│ │ │ │ │ ├─┬ @turf/line-segment@6.0.2
│ │ │ │ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ │ │ │ ├── @turf/invariant@6.1.2 deduped
│ │ │ │ │ │ └── @turf/meta@6.0.2 deduped
│ │ │ │ │ ├── @turf/meta@6.0.2 deduped
│ │ │ │ │ └─┬ geojson-rbush@3.1.2
│ │ │ │ │   ├── @turf/bbox@6.0.1 deduped
│ │ │ │ │   ├── @turf/helpers@6.1.4 deduped
│ │ │ │ │   ├── @turf/meta@6.0.2 deduped
│ │ │ │ │   └─┬ rbush@2.0.2
│ │ │ │ │     └── quickselect@1.1.1
│ │ │ │ ├── @turf/meta@6.0.2 deduped
│ │ │ │ └─┬ @turf/polygon-to-line@6.0.3
│ │ │ │   ├── @turf/helpers@6.1.4 deduped
│ │ │ │   └── @turf/invariant@6.1.2 deduped
│ │ │ ├── @turf/helpers@6.1.4 deduped
│ │ │ └── @turf/meta@6.0.2 deduped
│ │ ├── @turf/distance@6.0.1 deduped
│ │ ├── @turf/helpers@6.1.4 deduped
│ │ └── @turf/invariant@6.1.2 deduped
│ ├─┬ debug@4.1.1
│ │ └── ms@2.1.2
│ ├── live-moving-average@0.1.1
│ ├── lodash.throttle@4.1.1
│ └─┬ p-queue@6.3.0
│   ├── eventemitter3@4.0.0
│   └─┬ p-timeout@3.2.0
│     └── p-finally@1.0.0
└─┬ length-prefixed-stream@2.0.0
  ├── inherits@2.0.4
  ├─┬ readable-stream@3.6.0
  │ ├── inherits@2.0.4 deduped
  │ ├─┬ string_decoder@1.3.0
  │ │ └── safe-buffer@5.2.0
  │ └── util-deprecate@1.0.2
  └── varint@5.0.0
```

**Comment by derhuerst** [comment]
As of 9e2cb1627fc3e26f5a4ab383706c7795df770068, this is probably obsolete.
